//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENT
{
    using System;
    
    
    public class Comuna
    {
        
        private String mIdComuna;
        
        private String mNomComuna;
        
        private String mNomProvincia;
        
        private String mIdRegion;
        
        private String mNomRegion;
        
        public virtual String IdComuna
        {
            get
            {
                return this.mIdComuna;
            }
            set
            {
                this.mIdComuna = value;
            }
        }
        
        public virtual String NomComuna
        {
            get
            {
                return this.mNomComuna;
            }
            set
            {
                this.mNomComuna = value;
            }
        }
        
        public virtual String NomProvincia
        {
            get
            {
                return this.mNomProvincia;
            }
            set
            {
                this.mNomProvincia = value;
            }
        }
        
        public virtual String IdRegion
        {
            get
            {
                return this.mIdRegion;
            }
            set
            {
                this.mIdRegion = value;
            }
        }
        
        public virtual String NomRegion
        {
            get
            {
                return this.mNomRegion;
            }
            set
            {
                this.mNomRegion = value;
            }
        }
    }
}
