//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENT
{
    using System;
    
    
    public class Deudor
    {
        
        private String mRutDeudor;
        
        private Int32 mIdMandante;
        
        private String mNombreDeudor;
        
        private DateTime? mFechaIngreso;
        
        private String mIdUsuarioIngreso;
        
        private DateTime mFechaModif;
        
        private String mIdUsuarioModif;
        
        private String mRepLegalRut;
        
        private String mRepLegalNombre;
        
        private Int32? mIdTipoPersona;
        
        private Int32 mIdAsignacion;
        
        private String mObservacion;
        
        private String mObsSistema;
        
        private Int32 mIdEtapaCobranza;
        
        private Int32 mIdCampana;
        
        private String mCodUltimaGestionEj;
        
        private String mCodUltimaGestionJud;
        
        private Int32 mIdUltGestionEJ;
        
        private Int32 mIdUltGestionJud;
        
        private String mAdic1;
        
        private String mAdic2;
        
        private String mAdic3;
        
        private String mAdic4;
        
        private String mAdic5;
        
        private Int32 mIdUsuarioAsig;

        private Int32 mIdUsuarioAsigPor;

        private String mCampanaCliente;
        
        private Int32 mIdProbabilidadCobro;
        
        private Int32 mIdTipoCarga;
        private String mRut;
        private Int32? mIdCondicionPago;
        private String mIdSector;
        private DateTime? mFechaTerminoContrato;
        private String mRenovable;
        private String mResponsableComercial;

        public virtual String RutDeudor
        {
            get
            {
                return this.mRutDeudor;
            }
            set
            {
                this.mRutDeudor = value;
            }
        }
        
        public virtual Int32 IdMandante
        {
            get
            {
                return this.mIdMandante;
            }
            set
            {
                this.mIdMandante = value;
            }
        }

        public virtual String Renovable
        {
            get
            {
                return this.mRenovable;
            }
            set
            {
                this.mRenovable = value;
            }
        }
        
        public virtual String ResponsableComercial
        {
            get
            {
                return this.mResponsableComercial;
            }
            set
            {
                this.mResponsableComercial = value;
            }
        }

        public virtual DateTime? FechaTerminoContrato
        {
            get
            {
                return this.mFechaTerminoContrato;
            }
            set
            {
                this.mFechaTerminoContrato = value;
            }
        }

        public virtual String IdSector
        {
            get
            {
                return this.mIdSector;
            }
            set
            {
                this.mIdSector = value;
            }
        }

        public virtual Int32? IdCondicionPago
        {
            get
            {
                return this.mIdCondicionPago;
            }
            set
            {
                this.mIdCondicionPago = value;
            }
        }

        public virtual String NombreDeudor
        {
            get
            {
                return this.mNombreDeudor;
            }
            set
            {
                this.mNombreDeudor = value;
            }
        }
        
        public virtual DateTime? FechaIngreso
        {
            get
            {
                return this.mFechaIngreso;
            }
            set
            {
                this.mFechaIngreso = value;
            }
        }
        
        public virtual String IdUsuarioIngreso
        {
            get
            {
                return this.mIdUsuarioIngreso;
            }
            set
            {
                this.mIdUsuarioIngreso = value;
            }
        }
        
        public virtual DateTime FechaModif
        {
            get
            {
                return this.mFechaModif;
            }
            set
            {
                this.mFechaModif = value;
            }
        }
        
        public virtual String IdUsuarioModif
        {
            get
            {
                return this.mIdUsuarioModif;
            }
            set
            {
                this.mIdUsuarioModif = value;
            }
        }
        
        public virtual String RepLegalRut
        {
            get
            {
                return this.mRepLegalRut;
            }
            set
            {
                this.mRepLegalRut = value;
            }
        }
        
        public virtual String RepLegalNombre
        {
            get
            {
                return this.mRepLegalNombre;
            }
            set
            {
                this.mRepLegalNombre = value;
            }
        }
        
        public virtual Int32? IdTipoPersona
        {
            get
            {
                return this.mIdTipoPersona;
            }
            set
            {
                this.mIdTipoPersona = value;
            }
        }
        
        public virtual Int32 IdAsignacion
        {
            get
            {
                return this.mIdAsignacion;
            }
            set
            {
                this.mIdAsignacion = value;
            }
        }
        
        public virtual String Observacion
        {
            get
            {
                return this.mObservacion;
            }
            set
            {
                this.mObservacion = value;
            }
        }
        
        public virtual String ObsSistema
        {
            get
            {
                return this.mObsSistema;
            }
            set
            {
                this.mObsSistema = value;
            }
        }
        
        public virtual Int32 IdEtapaCobranza
        {
            get
            {
                return this.mIdEtapaCobranza;
            }
            set
            {
                this.mIdEtapaCobranza = value;
            }
        }
        
        public virtual Int32 IdCampana
        {
            get
            {
                return this.mIdCampana;
            }
            set
            {
                this.mIdCampana = value;
            }
        }
        
        public virtual String CodUltimaGestionEj
        {
            get
            {
                return this.mCodUltimaGestionEj;
            }
            set
            {
                this.mCodUltimaGestionEj = value;
            }
        }
        
        public virtual String CodUltimaGestionJud
        {
            get
            {
                return this.mCodUltimaGestionJud;
            }
            set
            {
                this.mCodUltimaGestionJud = value;
            }
        }
        
        public virtual Int32 IdUltGestionEJ
        {
            get
            {
                return this.mIdUltGestionEJ;
            }
            set
            {
                this.mIdUltGestionEJ = value;
            }
        }
        
        public virtual Int32 IdUltGestionJud
        {
            get
            {
                return this.mIdUltGestionJud;
            }
            set
            {
                this.mIdUltGestionJud = value;
            }
        }
        
        public virtual String Adic1
        {
            get
            {
                return this.mAdic1;
            }
            set
            {
                this.mAdic1 = value;
            }
        }
        
        public virtual String Adic2
        {
            get
            {
                return this.mAdic2;
            }
            set
            {
                this.mAdic2 = value;
            }
        }
        
        public virtual String Adic3
        {
            get
            {
                return this.mAdic3;
            }
            set
            {
                this.mAdic3 = value;
            }
        }
        
        public virtual String Adic4
        {
            get
            {
                return this.mAdic4;
            }
            set
            {
                this.mAdic4 = value;
            }
        }
        
        public virtual String Adic5
        {
            get
            {
                return this.mAdic5;
            }
            set
            {
                this.mAdic5 = value;
            }
        }
        
        public virtual Int32 IdUsuarioAsig
        {
            get
            {
                return this.mIdUsuarioAsig;
            }
            set
            {
                this.mIdUsuarioAsig = value;
            }
        }

        public virtual Int32 IdUsuarioAsigPor
        {
            get
            {
                return this.mIdUsuarioAsigPor;
            }
            set
            {
                this.mIdUsuarioAsigPor = value;
            }
        }

        public virtual String CampanaCliente
        {
            get
            {
                return this.mCampanaCliente;
            }
            set
            {
                this.mCampanaCliente = value;
            }
        }
        
        public virtual Int32 IdProbabilidadCobro
        {
            get
            {
                return this.mIdProbabilidadCobro;
            }
            set
            {
                this.mIdProbabilidadCobro = value;
            }
        }
        
        public virtual Int32 IdTipoCarga
        {
            get
            {
                return this.mIdTipoCarga;
            }
            set
            {
                this.mIdTipoCarga = value;
            }
        }

        public virtual String rut
        {
            get
            {
                return this.mRut;
            }
            set
            {
                this.mRut = value;
            }
        }
        
    }
}
