//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENT
{
    using System;
    
    
    public class EtapaCobranza
    {
        
        private Int32 mIdEtapaCobranza;
        
        private String mNomEtapaCobranza;
        
        private Int32 mActivo;
        
        public virtual Int32 IdEtapaCobranza
        {
            get
            {
                return this.mIdEtapaCobranza;
            }
            set
            {
                this.mIdEtapaCobranza = value;
            }
        }
        
        public virtual String NomEtapaCobranza
        {
            get
            {
                return this.mNomEtapaCobranza;
            }
            set
            {
                this.mNomEtapaCobranza = value;
            }
        }
        
        public virtual Int32 Activo
        {
            get
            {
                return this.mActivo;
            }
            set
            {
                this.mActivo = value;
            }
        }
    }
}
