//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENT
{
    using System;
    
    
    public class Gestiones
    {
        
        private Int32 mIdGestion;
        
        private String mRutDeudor;
        
        private Int32 mIdMandante;
        
        private Int32 mIdTipificacion;
        
        private DateTime mFechaIngreso;
        
        private String mHoraIngreso;
        
        private DateTime? mFechaCompromiso;
        
        private Int32? mMontoCompromiso;
        
        private String mObservaciones;
        
        private Int32? mIdTelefonoAsociado;
        
        private Int32? mIdDireccionAsociada;
        
        private DateTime mfecha_retiro;
        
        private DateTime? mFechaAgendamiento;
        
        private String mHoraAgendamiento;
        
        private Int32 mIdUsuario;
        
        private Int32 mIdCampana;
        
        private Int32 mProcesado;
        
        public virtual Int32 IdGestion
        {
            get
            {
                return this.mIdGestion;
            }
            set
            {
                this.mIdGestion = value;
            }
        }
        
        public virtual String RutDeudor
        {
            get
            {
                return this.mRutDeudor;
            }
            set
            {
                this.mRutDeudor = value;
            }
        }
        
        public virtual Int32 IdMandante
        {
            get
            {
                return this.mIdMandante;
            }
            set
            {
                this.mIdMandante = value;
            }
        }
        
        public virtual Int32 IdTipificacion
        {
            get
            {
                return this.mIdTipificacion;
            }
            set
            {
                this.mIdTipificacion = value;
            }
        }
        
        public virtual DateTime FechaIngreso
        {
            get
            {
                return this.mFechaIngreso;
            }
            set
            {
                this.mFechaIngreso = value;
            }
        }
        
        public virtual String HoraIngreso
        {
            get
            {
                return this.mHoraIngreso;
            }
            set
            {
                this.mHoraIngreso = value;
            }
        }
        
        public virtual DateTime? FechaCompromiso
        {
            get
            {
                return this.mFechaCompromiso;
            }
            set
            {
                this.mFechaCompromiso = value;
            }
        }
        
        public virtual Int32? MontoCompromiso
        {
            get
            {
                return this.mMontoCompromiso;
            }
            set
            {
                this.mMontoCompromiso = value;
            }
        }
        
        public virtual String Observaciones
        {
            get
            {
                return this.mObservaciones;
            }
            set
            {
                this.mObservaciones = value;
            }
        }
        
        public virtual Int32? IdTelefonoAsociado
        {
            get
            {
                return this.mIdTelefonoAsociado;
            }
            set
            {
                this.mIdTelefonoAsociado = value;
            }
        }
        
        public virtual Int32? IdDireccionAsociada
        {
            get
            {
                return this.mIdDireccionAsociada;
            }
            set
            {
                this.mIdDireccionAsociada = value;
            }
        }
        
        public virtual DateTime fecha_retiro
        {
            get
            {
                return this.mfecha_retiro;
            }
            set
            {
                this.mfecha_retiro = value;
            }
        }
        
        public virtual DateTime? FechaAgendamiento
        {
            get
            {
                return this.mFechaAgendamiento;
            }
            set
            {
                this.mFechaAgendamiento = value;
            }
        }
        
        public virtual String HoraAgendamiento
        {
            get
            {
                return this.mHoraAgendamiento;
            }
            set
            {
                this.mHoraAgendamiento = value;
            }
        }
        
        public virtual Int32 IdUsuario
        {
            get
            {
                return this.mIdUsuario;
            }
            set
            {
                this.mIdUsuario = value;
            }
        }
        
        public virtual Int32 IdCampana
        {
            get
            {
                return this.mIdCampana;
            }
            set
            {
                this.mIdCampana = value;
            }
        }
        
        public virtual Int32 Procesado
        {
            get
            {
                return this.mProcesado;
            }
            set
            {
                this.mProcesado = value;
            }
        }
    }
}
