//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENT
{
    using System;
    
    
    public class Mandante
    {
        
        private Int32 mIdMandante;
        
        private String mNomMandante;
        
        private String mRazonSocial;
        
        private String mGiro;
        
        private String mRut;
        
        private String mDireccion;
        
        private String mIdComuna;
        
        private String mTelefono;
        
        private String mRepLegalNombre;
        
        private String mRepLegalRut;
        
        private String mContactoNombre;
        
        private String mContactoEmail;
        
        private String mDeudaNomAdic1;
        
        private String mDeudaNomAdic2;
        
        private String mDeudaNomAdic3;
        
        private String mDeudaNomAdic4;
        
        private String mDeudaNomAdic5;
        
        private String mDeudaNomAdic6;
        
        private String mDeudaNomAdic7;
        
        private String mDeudaNomAdic8;
        
        private String mDeudaNomAdic9;
        
        private String mDeudaNomAdic10;
        
        private String mDeudorNomAdic1;
        
        private String mDeudorNomAdic2;
        
        private String mDeudorNomAdic3;
        
        private String mDeudorNomAdic4;
        
        private String mDeudorNomAdic5;
        
        private Double mTasaMaxConv;
        
        private Int32 mIdTipoInteres;
        
        private Int32 mIdTipoCliente;
        
        private Double mInteresMora;
        
        private Int32 mIdMoneda;
        
        private Int32 mActivo;
        
        private String mRutaLogo;
        
        private String mSkin;
        private Int32? mIdTipoTipificacion;

        public virtual Int32 IdMandante
        {
            get
            {
                return this.mIdMandante;
            }
            set
            {
                this.mIdMandante = value;
            }
        }
        
        public virtual String NomMandante
        {
            get
            {
                return this.mNomMandante;
            }
            set
            {
                this.mNomMandante = value;
            }
        }
        
        public virtual String RazonSocial
        {
            get
            {
                return this.mRazonSocial;
            }
            set
            {
                this.mRazonSocial = value;
            }
        }
        
        public virtual String Giro
        {
            get
            {
                return this.mGiro;
            }
            set
            {
                this.mGiro = value;
            }
        }
        
        public virtual String Rut
        {
            get
            {
                return this.mRut;
            }
            set
            {
                this.mRut = value;
            }
        }
        
        public virtual String Direccion
        {
            get
            {
                return this.mDireccion;
            }
            set
            {
                this.mDireccion = value;
            }
        }
        
        public virtual String IdComuna
        {
            get
            {
                return this.mIdComuna;
            }
            set
            {
                this.mIdComuna = value;
            }
        }
        
        public virtual String Telefono
        {
            get
            {
                return this.mTelefono;
            }
            set
            {
                this.mTelefono = value;
            }
        }
        
        public virtual String RepLegalNombre
        {
            get
            {
                return this.mRepLegalNombre;
            }
            set
            {
                this.mRepLegalNombre = value;
            }
        }
        
        public virtual String RepLegalRut
        {
            get
            {
                return this.mRepLegalRut;
            }
            set
            {
                this.mRepLegalRut = value;
            }
        }
        
        public virtual String ContactoNombre
        {
            get
            {
                return this.mContactoNombre;
            }
            set
            {
                this.mContactoNombre = value;
            }
        }
        
        public virtual String ContactoEmail
        {
            get
            {
                return this.mContactoEmail;
            }
            set
            {
                this.mContactoEmail = value;
            }
        }
        
        public virtual String DeudaNomAdic1
        {
            get
            {
                return this.mDeudaNomAdic1;
            }
            set
            {
                this.mDeudaNomAdic1 = value;
            }
        }
        
        public virtual String DeudaNomAdic2
        {
            get
            {
                return this.mDeudaNomAdic2;
            }
            set
            {
                this.mDeudaNomAdic2 = value;
            }
        }
        
        public virtual String DeudaNomAdic3
        {
            get
            {
                return this.mDeudaNomAdic3;
            }
            set
            {
                this.mDeudaNomAdic3 = value;
            }
        }
        
        public virtual String DeudaNomAdic4
        {
            get
            {
                return this.mDeudaNomAdic4;
            }
            set
            {
                this.mDeudaNomAdic4 = value;
            }
        }
        
        public virtual String DeudaNomAdic5
        {
            get
            {
                return this.mDeudaNomAdic5;
            }
            set
            {
                this.mDeudaNomAdic5 = value;
            }
        }
        
        public virtual String DeudaNomAdic6
        {
            get
            {
                return this.mDeudaNomAdic6;
            }
            set
            {
                this.mDeudaNomAdic6 = value;
            }
        }
        
        public virtual String DeudaNomAdic7
        {
            get
            {
                return this.mDeudaNomAdic7;
            }
            set
            {
                this.mDeudaNomAdic7 = value;
            }
        }
        
        public virtual String DeudaNomAdic8
        {
            get
            {
                return this.mDeudaNomAdic8;
            }
            set
            {
                this.mDeudaNomAdic8 = value;
            }
        }
        
        public virtual String DeudaNomAdic9
        {
            get
            {
                return this.mDeudaNomAdic9;
            }
            set
            {
                this.mDeudaNomAdic9 = value;
            }
        }
        
        public virtual String DeudaNomAdic10
        {
            get
            {
                return this.mDeudaNomAdic10;
            }
            set
            {
                this.mDeudaNomAdic10 = value;
            }
        }
        
        public virtual String DeudorNomAdic1
        {
            get
            {
                return this.mDeudorNomAdic1;
            }
            set
            {
                this.mDeudorNomAdic1 = value;
            }
        }
        
        public virtual String DeudorNomAdic2
        {
            get
            {
                return this.mDeudorNomAdic2;
            }
            set
            {
                this.mDeudorNomAdic2 = value;
            }
        }
        
        public virtual String DeudorNomAdic3
        {
            get
            {
                return this.mDeudorNomAdic3;
            }
            set
            {
                this.mDeudorNomAdic3 = value;
            }
        }
        
        public virtual String DeudorNomAdic4
        {
            get
            {
                return this.mDeudorNomAdic4;
            }
            set
            {
                this.mDeudorNomAdic4 = value;
            }
        }
        
        public virtual String DeudorNomAdic5
        {
            get
            {
                return this.mDeudorNomAdic5;
            }
            set
            {
                this.mDeudorNomAdic5 = value;
            }
        }
        
        public virtual Double TasaMaxConv
        {
            get
            {
                return this.mTasaMaxConv;
            }
            set
            {
                this.mTasaMaxConv = value;
            }
        }
        
        public virtual Int32 IdTipoInteres
        {
            get
            {
                return this.mIdTipoInteres;
            }
            set
            {
                this.mIdTipoInteres = value;
            }
        }
        
        public virtual Int32 IdTipoCliente
        {
            get
            {
                return this.mIdTipoCliente;
            }
            set
            {
                this.mIdTipoCliente = value;
            }
        }
        
        public virtual Double InteresMora
        {
            get
            {
                return this.mInteresMora;
            }
            set
            {
                this.mInteresMora = value;
            }
        }
        
        public virtual Int32 IdMoneda
        {
            get
            {
                return this.mIdMoneda;
            }
            set
            {
                this.mIdMoneda = value;
            }
        }
        
        public virtual Int32 Activo
        {
            get
            {
                return this.mActivo;
            }
            set
            {
                this.mActivo = value;
            }
        }
        
        public virtual String RutaLogo
        {
            get
            {
                return this.mRutaLogo;
            }
            set
            {
                this.mRutaLogo = value;
            }
        }
        
        public virtual String Skin
        {
            get
            {
                return this.mSkin;
            }
            set
            {
                this.mSkin = value;
            }
        }

        public virtual Int32? IdTipoTipificacion
        {
            get
            {
                return this.mIdTipoTipificacion;
            }
            set
            {
                this.mIdTipoTipificacion = value;
            }
        }
    }
}
