//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENT
{
    using System;
    
    
    public class MandanteArchivos
    {
        
        private Int32 mIdMandante;
        
        private Int32 mIdArchivo;
        
        private String mRutaArchivo;
        
        private Int32 mIdUsuarioIngreso;
        
        private DateTime mFechaIngreso;
        
        public virtual Int32 IdMandante
        {
            get
            {
                return this.mIdMandante;
            }
            set
            {
                this.mIdMandante = value;
            }
        }
        
        public virtual Int32 IdArchivo
        {
            get
            {
                return this.mIdArchivo;
            }
            set
            {
                this.mIdArchivo = value;
            }
        }
        
        public virtual String RutaArchivo
        {
            get
            {
                return this.mRutaArchivo;
            }
            set
            {
                this.mRutaArchivo = value;
            }
        }
        
        public virtual Int32 IdUsuarioIngreso
        {
            get
            {
                return this.mIdUsuarioIngreso;
            }
            set
            {
                this.mIdUsuarioIngreso = value;
            }
        }
        
        public virtual DateTime FechaIngreso
        {
            get
            {
                return this.mFechaIngreso;
            }
            set
            {
                this.mFechaIngreso = value;
            }
        }
    }
}
