//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENT
{
    using System;
    
    
    public class Mensaje
    {
        
        private Int32 mIdMensaje;
        
        private String mAsunto;
        
        private String mMensaje;
        
        private Int32 mIdUsuarioPara;
        
        private Int32 mIdUsuarioDe;
        
        private DateTime mFechaIngreso;
        
        private Int32 mLeido;
        
        public virtual Int32 IdMensaje
        {
            get
            {
                return this.mIdMensaje;
            }
            set
            {
                this.mIdMensaje = value;
            }
        }
        
        public virtual String Asunto
        {
            get
            {
                return this.mAsunto;
            }
            set
            {
                this.mAsunto = value;
            }
        }
        
        public virtual String MensajeObs
        {
            get
            {
                return this.mMensaje;
            }
            set
            {
                this.mMensaje = value;
            }
        }
        
        public virtual Int32 IdUsuarioPara
        {
            get
            {
                return this.mIdUsuarioPara;
            }
            set
            {
                this.mIdUsuarioPara = value;
            }
        }
        
        public virtual Int32 IdUsuarioDe
        {
            get
            {
                return this.mIdUsuarioDe;
            }
            set
            {
                this.mIdUsuarioDe = value;
            }
        }
        
        public virtual DateTime FechaIngreso
        {
            get
            {
                return this.mFechaIngreso;
            }
            set
            {
                this.mFechaIngreso = value;
            }
        }
        
        public virtual Int32 Leido
        {
            get
            {
                return this.mLeido;
            }
            set
            {
                this.mLeido = value;
            }
        }
    }
}
