//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENT
{
    using System;
    
    
    public class Moneda
    {
        
        private Int32 mIdMoneda;
        
        private String mNomMoneda;
        
        private Int32 mActivo;
        
        public virtual Int32 IdMoneda
        {
            get
            {
                return this.mIdMoneda;
            }
            set
            {
                this.mIdMoneda = value;
            }
        }
        
        public virtual String NomMoneda
        {
            get
            {
                return this.mNomMoneda;
            }
            set
            {
                this.mNomMoneda = value;
            }
        }
        
        public virtual Int32 Activo
        {
            get
            {
                return this.mActivo;
            }
            set
            {
                this.mActivo = value;
            }
        }
    }
}
