//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENT
{
    using System;
    
    
    public class PagosAirLiquide
    {
        
        private String mCOD_SUCURSAL;
        
        private Int32 mCOD_CLIENTE;
        
        private String mNOMBRE_CLIENTE;
        
        private String mSERIE;
        
        private String mESP;
        
        private String mDOCUMENTO;
        
        private String mMODALIDAD;
        
        private DateTime? mFECHA_EMISION;
        
        private DateTime? mFECHA_VENCIMIENTO;
        
        private String mREFERENCIA;
        
        private DateTime? mFECHA_REFERENCIA;
        
        private Double mMONTO_TITULO;
        
        private String mBANCO;
        
        private String mNRO_CHEQUE;
        
        private Double mVALOR_BAJA;
        
        private DateTime? mFECHA_VENCIMIENTO_CHEQUE;
        
        private Double mMONTO_TOTAL;
        
        private String mPORTADOR;
        
        public virtual String COD_SUCURSAL
        {
            get
            {
                return this.mCOD_SUCURSAL;
            }
            set
            {
                this.mCOD_SUCURSAL = value;
            }
        }
        
        public virtual Int32 COD_CLIENTE
        {
            get
            {
                return this.mCOD_CLIENTE;
            }
            set
            {
                this.mCOD_CLIENTE = value;
            }
        }
        
        public virtual String NOMBRE_CLIENTE
        {
            get
            {
                return this.mNOMBRE_CLIENTE;
            }
            set
            {
                this.mNOMBRE_CLIENTE = value;
            }
        }
        
        public virtual String SERIE
        {
            get
            {
                return this.mSERIE;
            }
            set
            {
                this.mSERIE = value;
            }
        }
        
        public virtual String ESP
        {
            get
            {
                return this.mESP;
            }
            set
            {
                this.mESP = value;
            }
        }
        
        public virtual String DOCUMENTO
        {
            get
            {
                return this.mDOCUMENTO;
            }
            set
            {
                this.mDOCUMENTO = value;
            }
        }
        
        public virtual String MODALIDAD
        {
            get
            {
                return this.mMODALIDAD;
            }
            set
            {
                this.mMODALIDAD = value;
            }
        }
        
        public virtual DateTime? FECHA_EMISION
        {
            get
            {
                return this.mFECHA_EMISION;
            }
            set
            {
                this.mFECHA_EMISION = value;
            }
        }
        
        public virtual DateTime? FECHA_VENCIMIENTO
        {
            get
            {
                return this.mFECHA_VENCIMIENTO;
            }
            set
            {
                this.mFECHA_VENCIMIENTO = value;
            }
        }
        
        public virtual String REFERENCIA
        {
            get
            {
                return this.mREFERENCIA;
            }
            set
            {
                this.mREFERENCIA = value;
            }
        }
        
        public virtual DateTime? FECHA_REFERENCIA
        {
            get
            {
                return this.mFECHA_REFERENCIA;
            }
            set
            {
                this.mFECHA_REFERENCIA = value;
            }
        }
        
        public virtual Double MONTO_TITULO
        {
            get
            {
                return this.mMONTO_TITULO;
            }
            set
            {
                this.mMONTO_TITULO = value;
            }
        }
        
        public virtual String BANCO
        {
            get
            {
                return this.mBANCO;
            }
            set
            {
                this.mBANCO = value;
            }
        }
        
        public virtual String NRO_CHEQUE
        {
            get
            {
                return this.mNRO_CHEQUE;
            }
            set
            {
                this.mNRO_CHEQUE = value;
            }
        }
        
        public virtual Double VALOR_BAJA
        {
            get
            {
                return this.mVALOR_BAJA;
            }
            set
            {
                this.mVALOR_BAJA = value;
            }
        }
        
        public virtual DateTime? FECHA_VENCIMIENTO_CHEQUE
        {
            get
            {
                return this.mFECHA_VENCIMIENTO_CHEQUE;
            }
            set
            {
                this.mFECHA_VENCIMIENTO_CHEQUE = value;
            }
        }
        
        public virtual Double MONTO_TOTAL
        {
            get
            {
                return this.mMONTO_TOTAL;
            }
            set
            {
                this.mMONTO_TOTAL = value;
            }
        }
        
        public virtual String PORTADOR
        {
            get
            {
                return this.mPORTADOR;
            }
            set
            {
                this.mPORTADOR = value;
            }
        }
    }
}
