//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENT
{
    using System;
    
    
    public class ProbabilidadCobro
    {
        
        private Int32 mIdProbabilidadCobro;
        
        private String mNomProbabilidadCobro;
        
        private Int32 mActivo;
        
        public virtual Int32 IdProbabilidadCobro
        {
            get
            {
                return this.mIdProbabilidadCobro;
            }
            set
            {
                this.mIdProbabilidadCobro = value;
            }
        }
        
        public virtual String NomProbabilidadCobro
        {
            get
            {
                return this.mNomProbabilidadCobro;
            }
            set
            {
                this.mNomProbabilidadCobro = value;
            }
        }
        
        public virtual Int32 Activo
        {
            get
            {
                return this.mActivo;
            }
            set
            {
                this.mActivo = value;
            }
        }
    }
}
