//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENT
{
    using System;
    
    
    public class Sucursal
    {
        
        private String mIdSucursal;
        
        private String mNomSucursal;
        
        private Int32 mActivo;
        
        public virtual String IdSucursal
        {
            get
            {
                return this.mIdSucursal;
            }
            set
            {
                this.mIdSucursal = value;
            }
        }
        
        public virtual String NomSucursal
        {
            get
            {
                return this.mNomSucursal;
            }
            set
            {
                this.mNomSucursal = value;
            }
        }
        
        public virtual Int32 Activo
        {
            get
            {
                return this.mActivo;
            }
            set
            {
                this.mActivo = value;
            }
        }
    }
}
