//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENT
{
    using System;
    
    
    public class sysdiagrams
    {
        
        private String mname;
        
        private Int32 mprincipal_id;
        
        private Int32 mdiagram_id;
        
        private Int32 mversion;
        
        private Boolean mdefinition;
        
        public virtual String name
        {
            get
            {
                return this.mname;
            }
            set
            {
                this.mname = value;
            }
        }
        
        public virtual Int32 principal_id
        {
            get
            {
                return this.mprincipal_id;
            }
            set
            {
                this.mprincipal_id = value;
            }
        }
        
        public virtual Int32 diagram_id
        {
            get
            {
                return this.mdiagram_id;
            }
            set
            {
                this.mdiagram_id = value;
            }
        }
        
        public virtual Int32 version
        {
            get
            {
                return this.mversion;
            }
            set
            {
                this.mversion = value;
            }
        }
        
        public virtual Boolean definition
        {
            get
            {
                return this.mdefinition;
            }
            set
            {
                this.mdefinition = value;
            }
        }
    }
}
