//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENT
{
    using System;
    
    
    public class TipoDocumento
    {
        
        private Int32 mIdTipoDocumento;
        
        private String mNomTipoDocumento;
        
        private Int32 mActivo;
        
        public virtual Int32 IdTipoDocumento
        {
            get
            {
                return this.mIdTipoDocumento;
            }
            set
            {
                this.mIdTipoDocumento = value;
            }
        }
        
        public virtual String NomTipoDocumento
        {
            get
            {
                return this.mNomTipoDocumento;
            }
            set
            {
                this.mNomTipoDocumento = value;
            }
        }
        
        public virtual Int32 Activo
        {
            get
            {
                return this.mActivo;
            }
            set
            {
                this.mActivo = value;
            }
        }
    }
}
