//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENT
{
    using System;
    
    
    public class TipoInteres
    {
        
        private Int32 mIdTipoInteres;
        
        private String mNomTipoInteres;
        
        private Int32 mActivo;
        
        public virtual Int32 IdTipoInteres
        {
            get
            {
                return this.mIdTipoInteres;
            }
            set
            {
                this.mIdTipoInteres = value;
            }
        }
        
        public virtual String NomTipoInteres
        {
            get
            {
                return this.mNomTipoInteres;
            }
            set
            {
                this.mNomTipoInteres = value;
            }
        }
        
        public virtual Int32 Activo
        {
            get
            {
                return this.mActivo;
            }
            set
            {
                this.mActivo = value;
            }
        }
    }
}
