//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENT
{
    using System;
    
    
    public class UbicTelefono
    {
        
        private Int32 mIdTelefono;
        
        private String mRut;
        
        private String mIdPais;
        
        private String mIdArea;
        
        private String mTelefono;
        
        private String mAnexo;
        
        private DateTime mFechaIngreso;
        
        private Int32 mIdUsuarioIngreso;
        
        private Int32 midTipoFono;
        
        private DateTime mFechaModif;
        
        private Int32 mIdUsuarioModif;
        
        private Int32 mIdEstadoUbic;
        
        private Int32 mIdProveedorUbic;
        
        private String mTelefonoDiscador;
        private String mNombreContacto;
        private String mTipoTelefono;
        private String mCargoContacto;

        public virtual Int32 IdTelefono
        {
            get
            {
                return this.mIdTelefono;
            }
            set
            {
                this.mIdTelefono = value;
            }
        }
        
        public virtual String Rut
        {
            get
            {
                return this.mRut;
            }
            set
            {
                this.mRut = value;
            }
        }


        public virtual String CargoContacto
        {
            get
            {
                return this.mCargoContacto;
            }
            set
            {
                this.mCargoContacto = value;
            }
        }

        public virtual String IdPais
        {
            get
            {
                return this.mIdPais;
            }
            set
            {
                this.mIdPais = value;
            }
        }
        
        public virtual String IdArea
        {
            get
            {
                return this.mIdArea;
            }
            set
            {
                this.mIdArea = value;
            }
        }
        
        public virtual String Telefono
        {
            get
            {
                return this.mTelefono;
            }
            set
            {
                this.mTelefono = value;
            }
        }
        
        public virtual String Anexo
        {
            get
            {
                return this.mAnexo;
            }
            set
            {
                this.mAnexo = value;
            }
        }
        
        public virtual DateTime FechaIngreso
        {
            get
            {
                return this.mFechaIngreso;
            }
            set
            {
                this.mFechaIngreso = value;
            }
        }
        
        public virtual Int32 IdUsuarioIngreso
        {
            get
            {
                return this.mIdUsuarioIngreso;
            }
            set
            {
                this.mIdUsuarioIngreso = value;
            }
        }
        
        public virtual Int32 idTipoFono
        {
            get
            {
                return this.midTipoFono;
            }
            set
            {
                this.midTipoFono = value;
            }
        }
        
        public virtual DateTime FechaModif
        {
            get
            {
                return this.mFechaModif;
            }
            set
            {
                this.mFechaModif = value;
            }
        }
        
        public virtual Int32 IdUsuarioModif
        {
            get
            {
                return this.mIdUsuarioModif;
            }
            set
            {
                this.mIdUsuarioModif = value;
            }
        }
        
        public virtual Int32 IdEstadoUbic
        {
            get
            {
                return this.mIdEstadoUbic;
            }
            set
            {
                this.mIdEstadoUbic = value;
            }
        }
        
        public virtual Int32 IdProveedorUbic
        {
            get
            {
                return this.mIdProveedorUbic;
            }
            set
            {
                this.mIdProveedorUbic = value;
            }
        }
        
        public virtual String TelefonoDiscador
        {
            get
            {
                return this.mTelefonoDiscador;
            }
            set
            {
                this.mTelefonoDiscador = value;
            }
        }
        
        public virtual String NombreContacto
        {
            get
            {
                return this.mNombreContacto;
            }
            set
            {
                this.mNombreContacto = value;
            }
        }

        public virtual String TipoTelefono
        {
            get
            {
                return this.mTipoTelefono;
            }
            set
            {
                this.mTipoTelefono = value;
            }
        }
    }
}
