//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENT
{
    using System;
    
    
    public class UsuarioMandante
    {
        
        private Int32 mIdUsuario;
        
        private Int32 mIdMandante;
        
        public virtual Int32 IdUsuario
        {
            get
            {
                return this.mIdUsuario;
            }
            set
            {
                this.mIdUsuario = value;
            }
        }
        
        public virtual Int32 IdMandante
        {
            get
            {
                return this.mIdMandante;
            }
            set
            {
                this.mIdMandante = value;
            }
        }
    }
}
